version: '3.8'

services:
  server:
    image: myapp-back-prod
    build:
      context: ./server # The context will pick this directory as the "build context"
      dockerfile: ./server/Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./server/:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - '3001:3000'
    container_name: myapp-back-prod-container
  client:
    image: myapp-front-prod
    build:
      context: ./client # The context will pick this directory as the "build context"
      dockerfile: /client/Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./client:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3000:80
    container_name: myapp-front-prod-container
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - server # wait for the frontend container to be started
      - client

